name: Merge

inputs:
  token:
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        token: ${{ inputs.token }}
        fetch-depth: 0
    - run: |
        git merge --ff-only "origin/${{ github.event.pull_request.head.ref }}"
        git push
