name: Merge

inputs:
  token:
    default: ${{ github.token }}
  gpg_private_key:
    default: ""
  gpg_passphrase:
    default: ""
  path:
    default: "."

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        fetch-depth: 0
    - if: inputs.gpg_private_key != ''
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        workdir: ${{ inputs.path }}
    - run: |
        gh pr checks "${{ github.event.pull_request.id }}" \
          --repo "${{ github.repository }}" \
          --required \
          --watch || true
    - if: inputs.gpg_private_key != ''
      run: |
        if git merge-base --is-ancestor \
          "${{ github.event.pull_request.base.ref }}" \
          "origin/${{ github.event.pull_request.head.ref }}"; then
          git merge --ff-only "origin/${{ github.event.pull_request.head.ref }}"
          git push
        else
          git config user.name "The Type Founders"
          git config user.email admin@thetypefounders.com
          git checkout "${{ github.event.pull_request.head.ref }}"
          git rebase "${{ github.event.pull_request.base.ref }}"
          git push --force
        fi
      shell: bash
      working-directory: ${{ inputs.path }}
    - if: inputs.gpg_private_key == ''
      run: |
        git merge --ff-only "origin/${{ github.event.pull_request.head.ref }}"
        git push
      shell: bash
      working-directory: ${{ inputs.path }}
