version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /checkout
      - /commit
      - /docker
      - /free
      - /merge
      - /tag
      - /security/leaks
      - /security/vulnerabilities
    schedule:
      interval: weekly
      day: sunday
      time: "00:00"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
