name: Commit

inputs:
  base:
    default: main
  head:
    default: ""
  token:
    default: ${{ github.token }}
  gpg_private_key:
    default: ""
  gpg_passphrase:
    default: ""
  message:
    required: true
  title:
    default: ""
  description:
    default: This pull request has been created automatically.
  reviewer:
    default: ""
  path:
    default: "."

runs:
  using: composite
  steps:
    - if: inputs.gpg_private_key != '' && inputs.gpg_passphrase != ''
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        workdir: ${{ inputs.path }}
    - run: |
        if git diff --cached --exit-code > /dev/null; then
          exit 0
        fi
        if [[ -z "${{ inputs.title }}" ]]; then
          title=$(echo "${{ inputs.message }}" | head -1)
        else
          title="${{ inputs.title }}"
        fi
        if [[ -z "${{ inputs.head }}" ]]; then
          head=ttf-$(echo "${title}" | tr "[:upper:]" "[:lower:]" | tr " " -)
        else
          head="${{ inputs.head }}"
        fi
        git config user.name "The Type Founders"
        git config user.email admin@thetypefounders.com
        git checkout -b "${head}"
        git commit -m "${{ inputs.message }}"
        git push --force --set-upstream origin "${head}"
        if gh pr list --base "${{ inputs.base }}" --head "${head}" | grep "${head}"; then
          exit 0
        fi
        arguments=(
          --base "${{ inputs.base }}"
          --head "${head}"
          --title "${title}"
          --body "${{ inputs.description }}"
        )
        if [[ -n "${{ inputs.reviewer }}" ]]; then
          arguments+=(--reviewer "${{ inputs.reviewer }}")
        fi
        gh pr create "${arguments[@]}"
      shell: bash
      working-directory: ${{ inputs.path }}
      env:
        GH_TOKEN: ${{ inputs.token }}
