name: Free

runs:
  using: composite
  steps:
    - uses: easimon/maximize-build-space@master
      with:
        remove-android: true
        remove-codeql: true
        remove-dotnet: true
        remove-haskell: true
