name: Checkout

inputs:
  repository:
    default: ${{ github.repository }}
  reference:
    default: ${{ github.sha }}
  token:
    default: ${{ github.token }}
  path:
    default: "."
  clean:
    default: true
  fetch-depth:
    default: 1
  exclude:
    default: ""
  include:
    default: "*"
  persist-credentials:
    default: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.reference }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        clean: ${{ inputs.clean }}
        fetch-depth: ${{ inputs.fetch-depth }}
        persist-credentials: ${{ inputs.persist-credentials }}
    - id: context
      run: |
        git lfs ls-files \
          --exclude "${{ inputs.exclude }}" \
          --include "${{ inputs.include }}" \
          --long | sort > .key
        key=$(cat .key | sha256sum | cut -d " " -f 1)
        echo "The key is ${key} based on $(cat .key | wc -l | xargs) files:"
        head .key
        echo ...
        echo "key=${key}" >> "${GITHUB_OUTPUT}"
        rm .key
      shell: bash
      working-directory: ${{ inputs.path }}
    - id: cache
      uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: v1-${{ steps.context.outputs.key }}
        restore-keys: v1-
    - run: git lfs pull
      shell: bash
      working-directory: ${{ inputs.path }}
    - if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: v1-${{ steps.context.outputs.key }}
