name: Checkout

inputs:
  repository:
    default: ${{ github.repository }}
  reference:
    default: ${{ github.sha }}
  token:
    default: ${{ github.token }}
  path:
    default: "."
  clean:
    default: true
  fetch-depth:
    default: 1

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.reference }}
        token: ${{ inputs.token }}
        path: ${{ inputs.path }}
        clean: ${{ inputs.clean }}
        fetch-depth: ${{ inputs.fetch-depth }}
    - id: key
      run: |
        git lfs ls-files --long | sort > .key
        hash=$(cat .key | sha256sum | cut -d " " -f 1)
        echo ${hash} based on $(cat .key | wc -l) files
        echo hash=${hash} >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.path }}
    - uses: actions/cache/restore@v3
      with:
        path: ${{ inputs.path || github.workspace }}/.git/lfs
        key: v1-${{ steps.key.outputs.hash }}
        restore-keys: v1-
    - run: git lfs pull
      shell: bash
      working-directory: ${{ inputs.path }}
    - uses: actions/cache/save@v3
      with:
        path: ${{ inputs.path }}/.git/lfs
        key: v1-${{ steps.key.outputs.hash }}
