name: Security Leaks

on:
  workflow_call:

permissions:
  contents: read

jobs:
  main:
    name: Leaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: $/security/leaks
